### ISSUE TITLE
Dynamic Copyright Year

### ISSUE THREAD

**Issue by Surya-Prakash-Reddy** [AmanDeep-21/codeforcesProfileComparator#3]
Make the copyright year in the footer as dynamic

**Comment by pururaj987** [comment]
Can you assign this to me @Surya-Prakash-Reddy ?

**Comment by pururaj987** [comment]
@AmanDeep-21 you can check PR #8

**Comment by Surya-Prakash-Reddy** [comment]
Closing as the PR is merged
